# -*- coding: utf-8 -*-
"""Homework: data talks club  - data extraction and ingestion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Te-AT0lfh0GpChg1Rbd0ByEKOHYtWXfm

# **Homework**: Data talks club data engineering zoomcamp Data loading workshop

Hello folks, let's practice what we learned - Loading data with the best practices of data engineering.

Here are the exercises we will do

# 1. Use a generator

Remember the concept of generator? Let's practice using them to futher our understanding of how they work.

Let's define a generator and then run it as practice.

**Answer the following questions:**

- **Question 1: What is the sum of the outputs of the generator for limit = 5?**
- **Question 2: What is the 13th number yielded**

I suggest practicing these questions without GPT as the purpose is to further your learning.
"""

def square_root_generator(limit):
    n = 1
    while n <= limit:
        yield n ** 0.5
        n += 1

# Example usage:
limit = 13
generator = square_root_generator(limit)

values_sum = 0
for sqrt_value in generator:
    print(sqrt_value)
    values_sum += sqrt_value

print(values_sum)

"""# 2. Append a generator to a table with existing data


Below you have 2 generators. You will be tasked to load them to duckdb and answer some questions from the data

1. Load the first generator and calculate the sum of ages of all people. Make sure to only load it once.
2. Append the second generator to the same table as the first.
3. **After correctly appending the data, calculate the sum of all ages of people.**



"""

def people_1():
    for i in range(1, 6):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 25 + i, "City": "City_A"}

for person in people_1():
    print(person)

def people_2():
    for i in range(3, 9):
        yield {"ID": i, "Name": f"Person_{i}", "Age": 30 + i, "City": "City_B", "Occupation": f"Job_{i}"}

for person in people_2():
    print(person)

"""# 3. Merge a generator

Re-use the generators from Exercise 2.

A table's primary key needs to be created from the start, so load your data to a new table with primary key ID.

Load your first generator first, and then load the second one with merge. Since they have overlapping IDs, some of the records from the first load should be replaced by the ones from the second load.

After loading, you should have a total of 8 records, and ID 3 should have age 33.

Question: **Calculate the sum of ages of all the people loaded as described above.**

# Solution: First make sure that the following modules are installed:
"""

# Commented out IPython magic to ensure Python compatibility.
# #Install the dependencies
# %%capture
# !pip install dlt[duckdb]

import dlt
import duckdb
from IPython.display import display

# Loading first generator
generators_pipeline = dlt.pipeline(destination="duckdb", dataset_name="generators")

info = generators_pipeline.run(
    people_1(), table_name="people", write_disposition="replace"
)

# Retrieving sum of ages from first generator
conn = duckdb.connect(f"{generators_pipeline.pipeline_name}.duckdb")

generator_1 = conn.sql("SELECT SUM(age) FROM generators.people").df()
display(generator_1)

# Loading second generator
info_1 = generators_pipeline.run(
    people_2(), table_name="people", write_disposition="append"
)

# Retrieving sum of ages from both generators
generators = conn.sql("SELECT SUM(age) FROM generators.people").df()
display(generators)

# New pipeline with primary key
info = generators_pipeline.run(
    people_1(), table_name="people_primary_key", write_disposition="replace", primary_key="id"
)
info = generators_pipeline.run(
    people_2(), table_name="people_primary_key", write_disposition="merge", primary_key="id"
)

# Retrieving sum of ages from both generators after merging
generators = conn.sql("SELECT SUM(age) FROM generators.people_primary_key").df()
display(generators)

"""Questions? difficulties? We are here to help.
- DTC data engineering course channel: https://datatalks-club.slack.com/archives/C01FABYF2RG
- dlt's DTC cohort channel: https://dlthub-community.slack.com/archives/C06GAEX2VNX
"""